### ISSUE TITLE
e0: provide info about how to execute a command within your editor

### ISSUE THREAD

**Issue by charliemirabile** [underground-software/ILKD_course_materials#11]
https://github.com/underground-software/ILKD_course_materials/blob/9640367b711186d531c2c161c132aaf7df079ca2/assignments/E0.md?plain=1#L88-L94

for nano `ctrl+t` (and maybe alt+f to put in current buffer if defaults to other buffer) for vim `r!command`

**Comment by theyoyojo** [comment]
Fixed by #50
