### ISSUE TITLE
Separate Kernel and userspace makefile in all assignments

### ISSUE THREAD

**Issue by charliemirabile** [underground-software/ILKD_course_materials#82]
it is messy to try and add code to build a module to a makefile for building userspace code. The modifications to `CC` and `CFLAGS` that you might want to use while building userspace might interfere with the kernel build process. 

At least E2 should be updated with a separate test folder like F2, and probably P2 as well

**Comment by andrade01986219** [comment]
Just made a pull request to address this in both E2 and P2

**Comment by charliemirabile** [comment]
Fixed by #85
